// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

type DbStubError = { message: string; code: string; hint: string; details: string };

function makeStubError(message: string): { data: null; error: DbStubError } {
  return {
    data: null,
    error: {
      message,
      code: "MISSING_SUPABASE_ENV",
      hint: "Configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY as environment variables.",
      details: "",
    },
  };
}

function makeStubChain(message: string, tableName?: string): any {
  const notAvailable = (): any => Promise.resolve(makeStubError(message));
  return new Proxy(
    {
      select: () => {
        const next: any = makeStubChain(message, tableName);
        next.order = () => notAvailable();
        next.eq = () => notAvailable();
        next.neq = () => notAvailable();
        next.maybeSingle = notAvailable;
        next.single = notAvailable;
        next.then = (onFulfilled: any, onRejected: any) =>
          Promise.resolve(makeStubError(message)).then(onFulfilled, onRejected);
        return next;
      },
      from: (_: string) => makeStubChain(message, _),
      insert: () => notAvailable(),
      upsert: () => notAvailable(),
      update: () => {
        const next: any = makeStubChain(message, tableName);
        next.eq = () => notAvailable();
        next.neq = () => notAvailable();
        return next;
      },
      delete: () => {
        const next: any = makeStubChain(message, tableName);
        next.eq = () => notAvailable();
        return next;
      },
      rpc: () => notAvailable(),
    },
    {
      get(target, prop, receiver) {
        if (prop === "auth") {
          return {
            getUser: () => Promise.resolve({ data: { user: null }, error: makeStubError(message).error }),
            getSession: () => Promise.resolve({ data: { session: null }, error: makeStubError(message).error }),
            signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: makeStubError(message).error }),
            signOut: () => Promise.resolve({ error: makeStubError(message).error }),
          };
        }
        if (prop in target) return Reflect.get(target, prop, receiver);
        return () => Promise.resolve(makeStubError(message));
      },
    },
  );
}

function createStubClient(message: string) {
  return makeStubChain(message) as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL / SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["VITE_SUPABASE_PUBLISHABLE_KEY / SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please configure your Supabase connection.`;
    console.error(`[Supabase Client] ${message} — Returning stub client (NO-OP).`);
    return createStubClient(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
