// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { resolveEnv } from "@/lib/env";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

type DbStubError = { message: string; code: string; hint: string; details: string };

function makeStubError(message: string): { data: null; error: DbStubError } {
  return {
    data: null,
    error: {
      message,
      code: "MISSING_SUPABASE_ENV",
      hint: "Configure SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY as environment variables.",
      details: "",
    },
  };
}

function makeStubChain(message: string, tableName?: string): any {
  const notAvailable = (): any => Promise.resolve(makeStubError(message));
  return new Proxy(
    {
      select: () => {
        const next: any = makeStubChain(message, tableName);
        next.order = () => notAvailable();
        next.eq = () => notAvailable();
        next.maybeSingle = notAvailable;
        next.single = notAvailable;
        next.then = (onFulfilled: any, onRejected: any) =>
          Promise.resolve(makeStubError(message)).then(onFulfilled, onRejected);
        return next;
      },
      from: (_: string) => makeStubChain(message, _),
      insert: () => notAvailable(),
      upsert: () => notAvailable(),
      update: () => {
        const next: any = makeStubChain(message, tableName);
        next.eq = () => notAvailable();
        next.neq = () => notAvailable();
        return next;
      },
      delete: () => {
        const next: any = makeStubChain(message, tableName);
        next.eq = () => notAvailable();
        return next;
      },
      rpc: () => notAvailable(),
    },
    {
      get(target, prop, receiver) {
        if (prop in target) return Reflect.get(target, prop, receiver);
        return () => Promise.resolve(makeStubError(message));
      },
    },
  );
}

function createStubAdminClient(message: string) {
  return makeStubChain(message) as ReturnType<typeof createClient<Database>>;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = resolveEnv("SUPABASE_URL", "VITE_SUPABASE_URL");
  const SUPABASE_SERVICE_ROLE_KEY = resolveEnv(
    "SUPABASE_SERVICE_ROLE_KEY",
    "VITE_SUPABASE_SERVICE_ROLE_KEY",
  );
  const SUPABASE_PUBLISHABLE_KEY = resolveEnv(
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
  );

  if (SUPABASE_PUBLISHABLE_KEY && !SUPABASE_SERVICE_ROLE_KEY) {
    console.warn(
      "[Supabase Admin] SUPABASE_SERVICE_ROLE_KEY not found — falling back to PUBLISHABLE key (RLS will be enforced — admin ops will fail).",
    );
  }

  const finalKey = SUPABASE_SERVICE_ROLE_KEY || SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !finalKey) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please configure your Supabase connection.`;
    console.error(`[Supabase Admin] ${message} — Returning stub client (NO-OP).`);
    return createStubAdminClient(message);
  }

  return createClient<Database>(SUPABASE_URL, finalKey, {
    global: {
      fetch: createSupabaseFetch(finalKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
